-- auto Generated on 2018-03-03 14:06:13 
-- DROP TABLE IF EXISTS `order`; 
CREATE TABLE order(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `uid` BIGINT NOT NULL DEFAULT -1 COMMENT 'uid',
    `remark` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'remark',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'order';
