DROP TABLE IF EXISTS brand;

CREATE TABLE brand(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  logo_url VARCHAR(255),
  selected BOOLEAN DEFAULT FALSE ,
  description VARCHAR(255)
) DEFAULT CHARSET=utf8mb4 ;

DROP TABLE IF EXISTS brand_food;
CREATE TABLE brand_food(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  price DECIMAL,
  brand_id BIGINT,
  selected BOOLEAN DEFAULT TRUE
) DEFAULT CHARSET=utf8mb4 ;

DROP TABLE IF EXISTS order_info ;

CREATE TABLE order_info(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  uid INTEGER NOT NULL ,
  remark VARCHAR(255),
  create_time BIGINT
) DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS order_item;

CREATE TABLE order_item(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT,
  food_id BIGINT,
  count INTEGER,
  create_time BIGINT
) DEFAULT CHARSET=utf8mb4;
